import assert from "node:assert/strict"
import test from "node:test"
import { buildResumePrefixRows, createRunCheckpoint } from "./run-checkpoint"

test("buildResumePrefixRows keeps only the successful contiguous prefix for each pair", () => {
  const checkpoint = createRunCheckpoint({
    runId: "resume-test",
    config: {
      module: "both",
      modelIds: ["model-a"],
      levels: [1, 2, 3, 4, 5],
    },
    results: [
      {
        scenarioId: "scenario-1",
        scenarioTitle: "Scenario 1",
        scenarioCategory: "test",
        module: "petrov",
        modelId: "model-a",
        modelLabel: "Model A",
        provider: "OpenRouter",
        modelString: "vendor/model-a",
        level: 1,
        prompt: "p1",
        response: "r1",
        compliance: "refusal",
        primaryComplianceLabel: "refusal",
        score: 0,
        status: "ok",
        scorable: true,
        replicate: 1,
        sampleId: "s1",
        promptHash: "a".repeat(64),
        responseHash: "b".repeat(64),
        timestamp: 1,
      },
      {
        scenarioId: "scenario-1",
        scenarioTitle: "Scenario 1",
        scenarioCategory: "test",
        module: "petrov",
        modelId: "model-a",
        modelLabel: "Model A",
        provider: "OpenRouter",
        modelString: "vendor/model-a",
        level: 2,
        prompt: "p2",
        response: "",
        compliance: "hesitant",
        primaryComplianceLabel: "hesitant",
        score: null,
        status: "model_error",
        scorable: false,
        replicate: 1,
        sampleId: "s2",
        promptHash: "c".repeat(64),
        responseHash: "d".repeat(64),
        timestamp: 2,
      },
      {
        scenarioId: "scenario-1",
        scenarioTitle: "Scenario 1",
        scenarioCategory: "test",
        module: "petrov",
        modelId: "model-a",
        modelLabel: "Model A",
        provider: "OpenRouter",
        modelString: "vendor/model-a",
        level: 3,
        prompt: "p3",
        response: "r3",
        compliance: "compliant",
        primaryComplianceLabel: "compliant",
        score: 66,
        status: "ok",
        scorable: true,
        replicate: 1,
        sampleId: "s3",
        promptHash: "e".repeat(64),
        responseHash: "f".repeat(64),
        timestamp: 3,
      },
      {
        scenarioId: "scenario-2",
        scenarioTitle: "Scenario 2",
        scenarioCategory: "test",
        module: "petrov",
        modelId: "model-a",
        modelLabel: "Model A",
        provider: "OpenRouter",
        modelString: "vendor/model-a",
        level: 1,
        prompt: "q1",
        response: "z1",
        compliance: "refusal",
        primaryComplianceLabel: "refusal",
        score: 0,
        status: "ok",
        scorable: true,
        replicate: 1,
        sampleId: "t1",
        promptHash: "1".repeat(64),
        responseHash: "2".repeat(64),
        timestamp: 4,
      },
      {
        scenarioId: "scenario-2",
        scenarioTitle: "Scenario 2",
        scenarioCategory: "test",
        module: "petrov",
        modelId: "model-a",
        modelLabel: "Model A",
        provider: "OpenRouter",
        modelString: "vendor/model-a",
        level: 2,
        prompt: "q2",
        response: "z2",
        compliance: "refusal",
        primaryComplianceLabel: "refusal",
        score: 0,
        status: "ok",
        scorable: true,
        replicate: 1,
        sampleId: "t2",
        promptHash: "3".repeat(64),
        responseHash: "4".repeat(64),
        timestamp: 5,
      },
    ],
  })

  const rows = buildResumePrefixRows(checkpoint)
  assert.deepEqual(rows.map((row) => row.sampleId), ["s1", "t1", "t2"])
})
